### ISSUE TITLE
Square .svg logo for branding

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/Branding#2]
Hey, i wanted to update the Swate info page today and i wanted to add a link to the nfdi4plants homepage next to the twitter and github logo.

![image](https://user-images.githubusercontent.com/39732517/106476759-aece3e00-64a7-11eb-9bcd-7ccc966413d6.png)

I first tried the logo provided currently, but as it is not square it does not fit very well.

I currently use the nfdi4plants organization profile image, but it lacks quality.

Maybe you @kMutagene could add a quare branding logo?

**Comment by kMutagene** [comment]
Done!

**Comment by Freymaurer** [comment]
Two Issues:

- The new icons seem to have a .svg "tail" on the left side. See the darkblue for example. It has a transparent area on the left.
- Now this one is purely optional. But next to the other icons it looks a bit convoluted, do you think it might be possible to have a cleaner more simple icon?
![image](https://user-images.githubusercontent.com/39732517/106570059-afadb100-6535-11eb-89d9-e583374acc21.png)

**Comment by kMutagene** [comment]
> The new icons seem to have a .svg "tail" on the left side

fixed 🚀

**Comment by Freymaurer** [comment]
The new icons look REALLY good! 🚀
