### ISSUE TITLE
Can you add text editable .svg in addition to .afdesign?

### ISSUE THREAD

**Issue by xiaoranzhou** [nfdi4plants/Branding#7]
Hi, I am now trying to create logo similar to the SWATE and SPAWN for the DMPG (Data Management Plan Generator)

Unfortunately I can not find an open source software to open the afdesign file, which could take me longer time to create a similar logo.

It will be greate If you can also upload a source file in svg with editable text.

**Comment by kMutagene** [comment]
Done, keep in mind that you have to download the correct font ;)
